Collections:
  - Name: AsterNet
    Metadata:
      Training Data: OCRDataset
      Training Techniques:
        - SGD
      Epochs: 6
      Batch Size:
      Training Resources:
      Architecture:
        - ResNetABI
        - TPSPreprocessor
        - AsterEncoder
        - AsterDecoder
    Paper:
      URL: https://ieeexplore.ieee.org/abstract/document/8395027
      Title: 'ASTER: An Attentional Scene Text Recognizer with Flexible Rectification'
    README: configs/textrecog/aster/README.md

Models:
  - Name: aster_only_academic
    In Collection: AsterNet
    Config: configs/textrecog/aster/aster_only_academic.py
    Metadata:
      Training Data:
        - Syn90k
        - SynthText
    Results:
      - Task: Text Recognition
        Dataset: IIIT5k
        Metrics:
          word_acc:
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc:
      - Task: Text Recognition
          Dataset: ICDAR2015
          Metrics:
            word_acc:
            - Task: Text Recognition
              Dataset: SVTP
              Metrics:
                word_acc:
            - Task: Text Recognition
              Dataset: CT80
              Metrics:
                word_acc:
    Weights:


'
