version: 2.1
jobs:
  build_cu101:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: gpu.nvidia.small
    steps:
      - checkout
      - run:
          name: Add python3.9 source
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:deadsnakes/ppa
      # Install python-dev for some packages which require libpython3.Xm.
      # Github's setup-python cannot install python3.9-dev, so we have to use apt install.
      # Set DEBIAN_FRONTEND=noninteractive to avoid some interactions.
      - run:
          name: Install Python-dev
          # command: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python${{matrix.python-version}}-dev
          command: |
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends python3.9-dev
            sudo apt install python-is-python3
      - run:
          name: Upgrade pip
          command: python -m pip install pip --upgrade
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 curl
      - run:
          name: Install librosa and soundfile
          command: python -m pip install librosa soundfile
      - run:
          name: Install lmdb
          command: python -m pip install lmdb
      - run:
          name: Install PyTorch
          # command: python -m pip install torch==${{matrix.torch}} torchvision==${{matrix.torchvision}} -f https://download.pytorch.org/whl/torch_stable.html
          command: python -m pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
      - run:
          name: Install mmocr dependencies
          # python -m pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch${{matrix.torch_version}}/index.html
          command: |
            python -m pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
            python -m pip install mmdet
            python -m pip install -r requirements.txt
      - run:
          name: Build and install
          command: |
            rm -rf .eggs
            python setup.py check -m -s
            TORCH_CUDA_ARCH_LIST=7.0 python -m pip install -e .
      - run:
          name: Run unittests and generate coverage report
          command: |
            coverage run --branch --source mmocr -m pytest tests/
            coverage xml
            coverage report -m

workflows:
  unit_tests:
    jobs:
      - build_cu101
