Collections:
- Name: CRNN
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adadelta
    Epochs: 5
    Batch Size: 256
    Training Resources: 4x GeForce GTX 1080 Ti
    Architecture:
      - VeryDeepVgg
      - CRNNDecoder
  Paper:
    URL: https://arxiv.org/pdf/1507.05717.pdf
    Title: 'An End-to-End Trainable Neural Network for Image-based Sequence Recognition and Its Application to Scene Text Recognition'
  README: configs/textrecog/crnn/README.md

Models:
  - Name: crnn_mini-vgg_5e_mj
    In Collection: CRNN
    Config: configs/textrecog/crnn/crnn_mini-vgg_5e_mj.py
    Metadata:
      Training Data: Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 80.5
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 81.5
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 86.5
    Weights: https://download.openmmlab.com/mmocr/textrecog/crnn/crnn_academic-a723a1c5.pth
