Collections:
- Name: TextSnake
  Metadata:
    Training Data: SCUT-CTW1500
    Training Techniques:
      - SGD with Momentum
    Training Resources: 8x GeForce GTX 1080 Ti
    Architecture:
      - ResNet
      - FPN_UNet
  Paper:
    URL: https://arxiv.org/abs/1807.01544.pdf
    Title: 'TextSnake: A Flexible Representation for Detecting Text of Arbitrary Shapes'
  README: configs/textdet/textsnake/README.md

Models:
  - Name: textsnake_r50_fpn_unet_1200e_ctw1500
    In Collection: TextSnake
    Config: configs/textdet/textsnake/textsnake_resnet50_fpn-unet_1200e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Text Detection
        Dataset: CTW1500
        Metrics:
          hmean-iou: 0.817
    Weights: https://download.openmmlab.com/mmocr/textdet/textsnake/textsnake_r50_fpn_unet_1200e_ctw1500-27f65b64.pth
