Collections:
- Name: TextSnake
  Metadata:
    Training Data: SCUT-CTW1500
    Training Techniques:
      - SGD with Momentum
    Training Resources: 1x NVIDIA A100-SXM4-80GB
    Architecture:
      - ResNet
      - FPN_UNet
  Paper:
    URL: https://arxiv.org/abs/1807.01544.pdf
    Title: 'TextSnake: A Flexible Representation for Detecting Text of Arbitrary Shapes'
  README: configs/textdet/textsnake/README.md

Models:
  - Name: textsnake_resnet50_fpn-unet_1200e_ctw1500
    Alias: TextSnake
    In Collection: TextSnake
    Config: configs/textdet/textsnake/textsnake_resnet50_fpn-unet_1200e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Text Detection
        Dataset: CTW1500
        Metrics:
          hmean-iou: 0.8286
    Weights: https://download.openmmlab.com/mmocr/textdet/textsnake/textsnake_resnet50_fpn-unet_1200e_ctw1500/textsnake_resnet50_fpn-unet_1200e_ctw1500_20220825_221459-c0b6adc4.pth

  - Name: textsnake_resnet50-oclip_fpn-unet_1200e_ctw1500
    In Collection: TextSnake
    Config: configs/textdet/textsnake/textsnake_resnet50-oclip_fpn-unet_1200e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Text Detection
        Dataset: CTW1500
        Metrics:
          hmean-iou: 0.8529
    Weights: https://download.openmmlab.com/mmocr/textdet/textsnake/textsnake_resnet50-oclip_fpn-unet_1200e_ctw1500/textsnake_resnet50-oclip_fpn-unet_1200e_ctw1500_20221101_134814-a216e5b2.pth
