Collections:
- Name: RobustScanner
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adam
    Epochs: 5
    Batch Size: 1024
    Training Resources: 16x GeForce GTX 1080 Ti
    Architecture:
      - ResNet31OCR
      - ChannelReductionEncoder
      - RobustScannerDecoder
  Paper: https://arxiv.org/pdf/2007.07542.pdf
  README: configs/textrecog/robust_scanner/README.md

Models:
  - Name: robustscanner_r31_academic
    In Collection: RobustScanner
    Config: configs/textrecog/robust_scanner/robustscanner_r31_academic.py
    Metadata:
      Training Data:
        - ICDAR2011
        - ICDAR2013
        - ICDAR2015
        - COCO text
        - IIIT5K
        - SynthText
        - SynthAdd
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 95.1
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 89.2
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 93.1
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 77.8
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 80.3
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 90.3
    Weights: https://download.openmmlab.com/mmocr/textrecog/robustscanner/robustscanner_r31_academic-5f05874f.pth
