Collections:
- Name: RobustScanner
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adam
    Epochs: 5
    Batch Size: 512
    Training Resources: 2x NVIDIA A100-SXM4-80GB
    Architecture:
      - ResNet31OCR
      - ChannelReductionEncoder
      - RobustScannerDecoder
  Paper:
    URL: https://arxiv.org/pdf/2007.07542.pdf
    Title: 'RobustScanner: Dynamically Enhancing Positional Clues for Robust Text Recognition'
  README: configs/textrecog/robust_scanner/README.md

Models:
  - Name: robustscanner_resnet31_5e_st-sub_mj-sub_sa_real
    In Collection: RobustScanner
    Config: configs/textrecog/robust_scanner/robustscanner_resnet31_5e_st-sub_mj-sub_sa_real.py
    Metadata:
      Training Data:
        - ICDAR2011
        - ICDAR2013
        - ICDAR2015
        - COCO text
        - IIIT5K
        - SynthText
        - SynthAdd
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 0.9510
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 0.8934
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 0.9320
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 0.7559
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 0.8078
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 0.8715
    Weights:
