Collections:
- Name: DBNet
  Metadata:
    Training Data: ICDAR2015
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
    Training Resources: 1x NVIDIA A100-SXM4-80GB
    Architecture:
      - ResNet
      - FPNC
  Paper:
    URL: https://arxiv.org/pdf/1911.08947.pdf
    Title: 'Real-time Scene Text Detection with Differentiable Binarization'
  README: configs/textdet/dbnet/README.md

Models:
  - Name: dbnet_resnet18_fpnc_1200e_icdar2015
    In Collection: DBNet
    Config: configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Text Detection
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.8169
    Weights: https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015/dbnet_resnet18_fpnc_1200e_icdar2015_20220825_221614-7c0e94f2.pth

  - Name: dbnet_resnet50-dcnv2_fpnc_1200e_icdar2015
    In Collection: DBNet
    Config: configs/textdet/dbnet/dbnet_resnet50-dcnv2_fpnc_1200e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Text Detection
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.8543
    Weights: https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_resnet50-dcnv2_fpnc_1200e_icdar2015/dbnet_resnet50-dcnv2_fpnc_1200e_icdar2015_20220828_124917-452c443c.pth
