Collections:
- Name: DBNet
  Metadata:
    Training Data: ICDAR2015
    Training Techniques:
      - SGD with Momentum
    Training Resources: 8x NVIDIA V100 GPUs
    Architecture:
      - ResNet
      - FPNC
  Paper: https://arxiv.org/pdf/1911.08947.pdf
  README: configs/textdet/dbnet/README.md

Models:
  - Name: dbnet_r18_fpnc_1200e_icdar2015
    In Collection: DBNet
    Config: configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Instance Segmentation
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.795
    Weights: https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth

  - Name: dbnet_r50dcnv2_fpnc_1200e_icdar2015
    In Collection: DBNet
    Config: configs/textdet/dbnet/dbnet_r50dcnv2_fpnc_1200e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Instance Segmentation
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.830
    Weights: https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_r50dcnv2_fpnc_sbn_1200e_icdar2015_20210325-91cef9af.pth
