Collections:
- Name: DBNet
  Metadata:
    Training Data: ICDAR2015
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
    Training Resources: 1x GeForce GTX 1080 Ti
    Architecture:
      - ResNet
      - FPNC
  Paper:
    URL: https://arxiv.org/pdf/1911.08947.pdf
    Title: 'Real-time Scene Text Detection with Differentiable Binarization'
  README: configs/textdet/dbnet/README.md

Models:
  - Name: dbnet_resnet18_fpnc_1200e_icdar2015
    In Collection: DBNet
    Config: configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Text Detection
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.795
    Weights: https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_r18_fpnc_sbn_1200e_icdar2015_20210329-ba3ab597.pth

  - Name: dbnet_resnet50-dcnv2_fpnc_1200e_icdar2015
    In Collection: DBNet
    Config: configs/textdet/dbnet/dbnet_resnet50-dcnv2_fpnc_1200e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Text Detection
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.840
    Weights: https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_r50dcnv2_fpnc_sbn_1200e_icdar2015_20211025-9fe3b590.pth
