Collections:
- Name: NRTR
  Metadata:
    Training Data: mixture
    Training Techniques:
      - SGD with Momentum
    Training Resources: 8x NVIDIA V100 GPUs
    Architecture:
      - Encoder
      - Decoder
      - Modality-Transform Block
  Paper: https://arxiv.org/pdf/1806.00926.pdf
  README: configs/textrecog/nrtr/README.md

Models:
  - Name: nrtr_r31_1by8_1by4_academic
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py
    Metadata:
      Training Data: SynthText
    Results:
      - Task: Regular Text Recognition
        Dataset: IIIT5K
        Metrics:
          acc: 93.9
        Dataset: SVT
        Metrics:
          acc: 90.0
        Dataset: ICDAR2013
        Metrics:
          acc: 93.5
      - Task: Irregular Text Recognition
        Dataset: ICDAR2015
        Metrics:
          acc: 74.5
        Dataset: SVTP
        Metrics:
          acc: 78.5
        Dataset: CT80
        Metrics:
          acc: 86.5
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_r31_academic_20210406-954db95e.pth

  - Name: nrtr_r31_1by16_1by8_academic
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py
    Metadata:
      Training Data: Syn90k
    Results:
      - Task: Regular Text Recognition
        Dataset: IIIT5K
        Metrics:
          acc: 94.7
        Dataset: SVT
        Metrics:
          acc: 87.5
        Dataset: ICDAR2013
        Metrics:
          acc: 93.3
      - Task: Irregular Text Recognition
        Dataset: ICDAR2015
        Metrics:
          acc: 75.1
        Dataset: SVTP
        Metrics:
          acc: 78.9
        Dataset: CT80
        Metrics:
          acc: 87.9
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_r31_1by8_1by4_academic_20210406-ce16e7cc.pth
