Collections:
- Name: NRTR
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adam
    Epochs: 6
    Batch Size: 384
    Training Resources: 1x NVIDIA A100-SXM4-80GB
    Architecture:
      - CNN
      - NRTREncoder
      - NRTRDecoder
  Paper:
    URL: https://arxiv.org/pdf/1806.00926.pdf
    Title: 'NRTR: A No-Recurrence Sequence-to-Sequence Model For Scene Text Recognition'
  README: configs/textrecog/nrtr/README.md

Models:
  - Name: nrtr_modality-transform_6e_st_mj
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_modality-transform_6e_st_mj.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 0.9150
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 0.8825
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 0.9369
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 0.7232
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 0.7783
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 0.7500
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_modality-transform_6e_st_mj/nrtr_modality-transform_6e_st_mj_20220916_103322-bd9425be.pth
  - Name: nrtr_resnet31-1by8-1by4_6e_st_mj
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_resnet31-1by8-1by4_6e_st_mj.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 0.9483
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 0.8825
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 0.9507
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 0.7559
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 0.8016
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 0.8889
    Weights: https://download.openmmlab.com/mmocr/textrecog/nrtr/nrtr_resnet31-1by8-1by4_6e_st_mj/nrtr_resnet31-1by8-1by4_6e_st_mj_20220916_103322-a6a2a123.pth
  - Name: nrtr_resnet31-1by16-1by8_6e_st_mj
    In Collection: NRTR
    Config: configs/textrecog/nrtr/nrtr_resnet31-1by16-1by8_6e_st_mj.py
    Metadata:
      Training Data:
        - SynthText
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 0.9470
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 0.8964
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 0.9399
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 0.7357
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 0.7969
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 0.8854
    Weights:
