Collections:
- Name: FCENet
  Metadata:
    Training Data: SCUT-CTW1500
    Training Techniques:
      - SGD with Momentum
    Training Resources: 1x Tesla A100
    Architecture:
      - ResNet50 with DCNv2
      - FPN
      - FCEHead
  Paper:
    URL: https://arxiv.org/abs/2002.02709.pdf
    Title: 'FourierNet: Compact mask representation for instance segmentation using differentiable shape decoders'
  README: configs/textdet/fcenet/README.md

Models:
  - Name: fcenet_r50dcnv2_fpn_1500e_ctw1500
    In Collection: FCENet
    Config: configs/textdet/fcenet/fcenet_r50dcnv2_fpn_1500e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Text Detection
        Dataset: CTW1500
        Metrics:
          hmean-iou: 0.8500
    Weights: https://download.openmmlab.com/mmocr/textdet/fcenet/fcenet_r50dcnv2_fpn_1500e_ctw1500_20211022-e326d7ec.pth
  - Name: fcenet_r50_fpn_1500e_icdar2015
    In Collection: FCENet
    Config: configs/textdet/fcenet/fcenet_r50_fpn_1500e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Text Detection
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.8528
    Weights: https://download.openmmlab.com/mmocr/textdet/fcenet/fcenet_r50_fpn_1500e_icdar2015_20211022-daefb6ed.pth
