Collections:
- Name: TPS-CRNN
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adadelta
    Epochs: 5
    Batch Size: 256
    Training Resources: 4x GeForce GTX 1080 Ti
    Architecture:
      - TPSPreprocessor
      - VeryDeepVgg
      - CRNNDecoder
      - CTCLoss
  Paper:
    - https://arxiv.org/pdf/1507.05717.pdf
    - https://arxiv.org/pdf/1603.03915.pdf
  README: configs/textrecog/tps/README.md

Models:
  - Name: crnn_tps_academic_dataset
    In Collection: TPS-CRNN
    Config: configs/textrecog/tps/crnn_tps_academic_dataset.py
    Metadata:
      Training Data: Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 80.8
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 81.3
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 85.0
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 59.6
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 68.1
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 53.8
    Weights: https://download.openmmlab.com/mmocr/textrecog/tps/crnn_tps_academic_dataset_20210510-d221a905.pth
