Collections:
- Name: PSENet
  Metadata:
    Training Data: ICDAR SCUT-CTW1500
    Training Techniques:
      - Adam
    Training Resources: 8x GeForce GTX 1080 Ti
    Architecture:
      - ResNet
      - FPNF
  Paper:
    URL: https://arxiv.org/abs/1806.02559.pdf
    Title: 'Shape Robust Text Detection with Progressive Scale Expansion Network'
  README: configs/textdet/psenet/README.md

Models:
  - Name: psenet_r50_fpnf_600e_ctw1500
    In Collection: PSENet
    Config: configs/textdet/psenet/psenet_r50_fpnf_600e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Text Detection
        Dataset: CTW1500
        Metrics:
          hmean-iou: 0.784
    Weights: https://download.openmmlab.com/mmocr/textdet/psenet/psenet_r50_fpnf_600e_ctw1500_20210401-216fed50.pth

  - Name: psenet_r50_fpnf_600e_icdar2015
    In Collection: PSENet
    Config: configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Text Detection
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.807
    Weights: https://download.openmmlab.com/mmocr/textdet/psenet/psenet_r50_fpnf_600e_icdar2015-c6131f0d.pth

  - Name: psenet_r50_fpnf_600e_icdar2015
    In Collection: PSENet
    Config: configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py
    Metadata:
      Training Data: ICDAR2017 ICDAR2015
    Results:
      - Task: Text Detection
        Dataset: ICDAR2017 ICDAR2015
        Metrics:
          hmean-iou: 0.847
    Weights: https://download.openmmlab.com/mmocr/textdet/psenet/psenet_r50_fpnf_600e_icdar2015_pretrain-eefd8fe6.pth
