Collections:
- Name: SAR
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adam
    Training Resources: 48x GeForce GTX 1080 Ti
    Epochs: 5
    Batch Size: 3072
    Architecture:
      - ResNet31OCR
      - SAREncoder
      - ParallelSARDecoder
  Paper:
    URL: https://arxiv.org/pdf/1811.00751.pdf
    Title: 'Show, Attend and Read:A Simple and Strong Baseline for Irregular Text Recognition'
  README: configs/textrecog/sar/README.md

Models:
  - Name: sar_r31_parallel_decoder_academic
    In Collection: SAR
    Config: configs/textrecog/sar/sar_r31_parallel_decoder_academic.py
    Metadata:
      Training Data:
        - ICDAR2011
        - ICDAR2013
        - ICDAR2015
        - COCO text
        - IIIT5K
        - SynthText
        - SynthAdd
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 95.2
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 89.5
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 93.7
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 79.2
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 81.9
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 89.6
    Weights: https://download.openmmlab.com/mmocr/textrecog/sar/sar_r31_parallel_decoder_academic-dba3a4a3.pth

  - Name: sar_r31_sequential_decoder_academic
    In Collection: SAR
    Config: configs/textrecog/sar/sar_r31_sequential_decoder_academic.py
    Metadata:
      Training Data:
        - ICDAR2011
        - ICDAR2013
        - ICDAR2015
        - COCO text
        - IIIT5K
        - SynthText
        - SynthAdd
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 95.2
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 88.3
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 92.6
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 78.7
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 81.9
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 90.3
    Weights: https://download.openmmlab.com/mmocr/textrecog/sar/sar_r31_sequential_decoder_academic-d06c9a8e.pth
