Collections:
- Name: PANet
  Metadata:
    Training Data: ICDARDataset
    Training Techniques:
      - Adam
    Training Resources: 8x NVIDIA V100 GPUs
    Architecture:
      - ResNet
      - FPEM_FFM
  Paper: https://arxiv.org/pdf/1803.01534.pdf
  README: configs/textdet/panet/README.md

Models:
  - Name: panet_r18_fpem_ffm_600e_ctw1500
    In Collection: PANet
    Config: configs/textdet/panet/panet_r18_fpem_ffm_600e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Instance Segmentation
        Dataset: CTW1500
        Metrics:
          hmean-iou: 0.806
    Weights: https://download.openmmlab.com/mmocr/textdet/panet/panet_r18_fpem_ffm_sbn_600e_ctw1500_20210219-3b3a9aa3.pth

  - Name: panet_r18_fpem_ffm_600e_icdar2015
    In Collection: PANet
    Config: configs/textdet/panet/panet_r18_fpem_ffm_600e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Instance Segmentation
        Dataset: ICDAR2015
        Metrics:
          hmean-iou: 0.791
    Weights: https://download.openmmlab.com/mmocr/textdet/panet/panet_r18_fpem_ffm_sbn_600e_icdar2015_20210219-42dbe46a.pth

  - Name: panet_r50_fpem_ffm_600e_icdar2017
    In Collection: PANet
    Config: configs/textdet/panet/panet_r50_fpem_ffm_600e_icdar2017.py
    Metadata:
      Training Data: ICDAR2017
    Results:
      - Task: Instance Segmentation
        Dataset: ICDAR2017
        Metrics:
          hmean-iou:
    Weights:
